server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/double_color_ball?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: JinDie$20210701
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  cache:
    type: caffeine
    caffeine:
      # 最多缓存50个不同查询条件的结果，10分钟无访问后过期
      spec: maximumSize=50,expireAfterAccess=600s

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      id-type: auto

logging:
  level:
    com.dcb: debug
